/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/banana-v1-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.banana.geometry} material={materials.skin} rotation={[2.51, 0.08, -2.98]} />
    </group>
  )
}

useGLTF.preload('/banana-v1-transformed.glb')
